[project]
name = "tender-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Said Arr", email = "busarrazouaki@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.7.15",
    "langchain-openai>=1.6.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
tender-assistant = "tender_assistant:main"

[build-system]
requires = ["uv_build>=0.11.24,<0.12.0"]
build-backend = "uv_build"
